import { MessageRole, MessageTone, MessageType } from '@/interfaces';

export const MESSAGES: MessageType[] = [
  {
    id: '1',
    role: MessageRole.USER,
    content: 'Can you help me with my problem?',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '2',
    role: MessageRole.EXPERT,
    content: "No, I can't help you with that.",
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '3',
    role: MessageRole.USER,
    content: 'Then what should I do?',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '4',
    role: MessageRole.EXPERT,
    content: 'You should try to fix it yourself.',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '5',
    role: MessageRole.USER,
    content: "But I don't know how to fix it.",
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '6',
    role: MessageRole.EXPERT,
    content: 'Anyway, I can help you with your problem.',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '7',
    role: MessageRole.USER,
    content: 'Thank you!',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '8',
    role: MessageRole.EXPERT,
    content: "You're welcome!",
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '9',
    role: MessageRole.USER,
    content: 'What is the best way to fix it?',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '11',
    role: MessageRole.USER,
    content: 'What is the best way to contact the support team?',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '12',
    role: MessageRole.EXPERT,
    content: 'You should contact the support team through the app.',
    createdAt: new Date(),
    tone: MessageTone.FRIENDLY,
  },
  {
    id: '13',
    role: MessageRole.USER,
    content: "Where can I find the support team? I can't find it.",
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '14',
    role: MessageRole.EXPERT,
    content: 'You should contact the support team through the app.',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '15',
    role: MessageRole.USER,
    content: 'Well, is that located in the general settings?',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '16',
    role: MessageRole.EXPERT,
    content: 'Yes, you can find it in the general settings.',
    createdAt: new Date(),
    tone: MessageTone.FRIENDLY,
  },
  {
    id: '17',
    role: MessageRole.USER,
    content: 'Thank you!',
    createdAt: new Date(),
    tone: MessageTone.NEUTRAL,
  },
  {
    id: '18',
    role: MessageRole.EXPERT,
    content: "You're welcome!",
    createdAt: new Date(),
    tone: MessageTone.SARCASTIC,
  },
];
